public class HelloWorld {
    
    static public String sayHello() {
        // Anup Scenario 1 - US1 originate from DEV1
        // Added change here that will be deployed to SIT
        // 
        // Anup Scenario 1 - US2 originate from DEV2 with update
        // Added change here that will be deployed to SIT
        // Will there be a merge conflict? Since this code came from SIT and there is no new version of the code in SIT
    
        return 'Hello World';
    }


}